services:
  minirentcal:
    container_name: MiniRentCalWebapp
    image: ${DOCKER_REGISTRY-}minirentcal
    build:
      context: .
      dockerfile: MiniRentCal/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPasswordHere 
      - ConnectionStrings__DefaultConnection=Server=db;Database=Azure_backup;TrustServerCertificate=True;User Id=sa;Password=YourStrong!Passw0rd;
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ~/.aspnet/https:/https:ro

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: MiniRentalSqlServer
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  sqldata:
    name: sql_data