services:
  minirentcal:
    container_name: MiniRentCalWebapp
    image: ${DOCKER_REGISTRY-}minirentcal
    build:
      context: .
      dockerfile: MiniRentCal/Dockerfile
    ports:
      - "5000:8080" # Map host port 5000 to container port 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: MiniRentalSqlServer
    ports:
    - "1433:1433" # Map host port 1433 to container port 1433
    environment:
        SA_PASSWORD: "YourStrong!Passw0rd"
        ACCEPT_EULA: "Y"
    networks:
    - app-network  

networks:
  app-network:
    driver: bridge